<html>
<head>
<title>PyErr_Display</title>
<meta name='robots' content='noindex,nofollow'>
<meta name='generator' content='GLOBAL-5.8.1'>
</head>
<body text='#191970' bgcolor='#f5f5dc' vlink='gray'>
<pre>
<a href='../S/2614.html#L2151'>PyErr_Display</a>    2151 Modules/_testcapimodule.c     PyErr_Display((PyObject *) Py_TYPE(value), value, tb);
<a href='../S/2623.html#L76'>PyErr_Display</a>      76 Modules/atexitmodule.c                 PyErr_Display(exc_type, exc_value, exc_tb);
<a href='../S/3138.html#L1479'>PyErr_Display</a>    1479 Python/pythonrun.c             PyErr_Display(exception2, v2, tb2);
<a href='../S/3138.html#L1481'>PyErr_Display</a>    1481 Python/pythonrun.c             PyErr_Display(exception, v, tb);
<a href='../S/3138.html#L1490'>PyErr_Display</a>    1490 Python/pythonrun.c         PyErr_Display(exception, v, tb);
<a href='../S/3144.html#L191'>PyErr_Display</a>     191 Python/sysmodule.c     PyErr_Display(exc, value, tb);
</pre>
</body>
</html>
