<html>
<head>
<title>PyException_GetTraceback</title>
<meta name='robots' content='noindex,nofollow'>
<meta name='generator' content='GLOBAL-5.8.1'>
</head>
<body text='#191970' bgcolor='#f5f5dc' vlink='gray'>
<pre>
<a href='../S/2614.html#L2150'>PyException_GetTraceback</a> 2150 Modules/_testcapimodule.c     tb = PyException_GetTraceback(value);
<a href='../S/3106.html#L110'>PyException_GetTraceback</a>  110 Python/errors.c         tb = PyException_GetTraceback(value);
<a href='../S/3138.html#L1513'>PyException_GetTraceback</a> 1513 Python/pythonrun.c     tb = PyException_GetTraceback(value);
</pre>
</body>
</html>
