<html>
<head>
<title>PyException_SetContext</title>
<meta name='robots' content='noindex,nofollow'>
<meta name='generator' content='GLOBAL-5.8.1'>
</head>
<body text='#191970' bgcolor='#f5f5dc' vlink='gray'>
<pre>
<a href='../S/2789.html#L274'>PyException_SetContext</a>  274 Objects/exceptions.c     PyException_SetContext(self, arg);
<a href='../S/3106.html#L99'>PyException_SetContext</a>   99 Python/errors.c                     PyException_SetContext(o, NULL);
<a href='../S/3106.html#L104'>PyException_SetContext</a>  104 Python/errors.c             PyException_SetContext(value, exc_value);
</pre>
</body>
</html>
